---
abstract: 'Distributed Project Management Tool'
author:
  - 'Mark Lawrence <nomad@null.net>'
build_requires:
  Exporter::Tidy: '0'
  ExtUtils::MakeMaker: '6.59'
  File::chdir: '0'
  FindBin: '0'
  Test::Fatal: '0'
  Test::More: '0'
configure_requires:
  CPAN::Meta: '0'
  Cwd: '0'
  ExtUtils::MakeMaker: '6.59'
  File::Spec: '0'
  FindBin: '0'
  Path::Tiny: '0'
  Pod::Select: '0'
  Time::Piece: '0'
dynamic_config: '0'
generated_by: 'Module::Install version 1.08, CPAN::Meta::Converter version 2.140640'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: App-bif
no_index:
  directory:
    - inc
    - share
    - t
    - xt
  package:
    - Bif::DB::db
    - Bif::DB::st
    - Bif::DBW::db
    - Bif::DBW::st
    - Bif::OK
    - Bif::Error
requires:
  AnyEvent: '0'
  Config::Tiny: '2.19'
  Coro: '0'
  Coro::Handle: '0'
  DBD::SQLite: '1.42'
  DBIx::ThinSQL: v0.0.18
  DBIx::ThinSQL::SQLite: v0.0.10
  Digest::SHA: '0'
  File::HomeDir: '0'
  File::ShareDir: '0'
  IO::Pager: '0.24'
  IO::Prompt::Tiny: '0'
  JSON: '0'
  Log::Any: '0'
  Log::Any::Adapter: '0.11'
  Log::Any::Plugin::Levels: '0'
  OptArgs: v0.1.6
  POSIX: '0'
  Path::Tiny: '0.019'
  Proc::InvokeEditor: '0'
  Role::Basic: '0'
  Sys::Cmd: v0.81.6
  Term::ANSIColor: '0'
  Term::Size: '0'
  Text::Autoformat: '0'
  Text::FormatTable: '0'
  Time::Duration: '0'
  locale: '0'
  perl: v5.10.0
resources:
  bugtracker: bif://bifax.org/bif/
  homepage: http://bifax.org/bif/
  repository: git://bifax.org/bif.git/
version: 0.1.0_18
