=head1 NAME

bif-doc-table-projects - project current meta data

=head1 VERSION

0.1.0_10 (2014-04-17)

=head1 DEFINITION

    #!sqlite
    CREATE TABLE projects (
        id integer NOT NULL PRIMARY KEY,
        parent_id integer,
        name varchar(40) NOT NULL,
        title varchar(1024) NOT NULL,
        path varchar collate nocase UNIQUE,
        status_id integer NOT NULL DEFAULT -1,
        FOREIGN KEY(id) REFERENCES topics(id)
            ON DELETE CASCADE
        FOREIGN KEY(parent_id) REFERENCES projects(id)
            ON DELETE CASCADE,
        FOREIGN KEY(status_id,id) REFERENCES project_status(id,project_id)
            DEFERRABLE INITIALLY DEFERRED
    )

=head1 DESCRIPTION

Table C<projects> contains the project-specific meta data for a topic.
Rows should only be inserted into this table by
L<func_new_project()|bif-doc-func-new-project> and only updated by
triggers on the L<projects_tomerge|bif-doc-table-projects-tomerge>
table. Deleting directly from this table is fine.

=head1 AFFECTED TABLES

=over

=item * L<projects_tree|bif-doc-table-projects-tree>

Modified on INSERT, UPDATE, and DELETE.

=item * L<projects_tomerge|bif-doc-table-projects-tomerge>

Cascading DELETEs.

=item * L<updates|bif-doc-table-updates>

Cascading DELETEs.

=back

=head1 SEE ALSO

L<bif-doc-func-new-project>,  L<bif-doc-table-topics>,
L<bif-doc-table-projects-tomerge>, L<bif-doc-table-project-status>,
L<bif-doc-table-projects-tree>, L<bif-doc-table-updates>

=head1 AUTHOR

Mark Lawrence E<lt>nomad@null.netE<gt>

=head1 COPYRIGHT AND LICENSE

Copyright 2013-2014 Mark Lawrence <nomad@null.net>

This program is free software; you can redistribute it and/or modify it
under the terms of the GNU General Public License as published by the
Free Software Foundation; either version 3 of the License, or (at your
option) any later version.

