=head1 NAME

bif-register -  register with a remote repository

=head1 VERSION

0.1.0_10 (2014-04-17)

=head1 SYNOPSIS

    bif register HUB [OPTIONS...]

=head1 DESCRIPTION

The C<bif register> command connects to a hub (a remote repository) to
obtain the list of projects hosted there. The project list is stored
locally and is used by the C<import> and C<push> commands when
communicating with the hub.

A hub can have an alias which useable with all of the hub-aware
commands (import,export,push) to save typing the full address.

If C<HUB> is a network address like C<an.organisation@a.provider> then
the default alias will be C<an.organisation>.  If C<hub> is a
filesystem path then the default alias is the path basename.

=head1 ARGUMENTS & OPTIONS

=over

=item HUB

The location of a remote hub.

=item --alias, -a

Override the default alias for the HUB.

=back

=head1 SEE ALSO

L<bif>(1)

=head1 AUTHOR

Mark Lawrence E<lt>nomad@null.netE<gt>

=head1 COPYRIGHT AND LICENSE

Copyright 2013-2014 Mark Lawrence <nomad@null.net>

This program is free software; you can redistribute it and/or modify it
under the terms of the GNU General Public License as published by the
Free Software Foundation; either version 3 of the License, or (at your
option) any later version.

