=head1 NAME

bif-init -  create new bif repository

=head1 VERSION

0.1.0_10 (2014-04-17)

=head1 SYNOPSIS

    bif init [DIRECTORY] [OPTIONS...]

=head1 DESCRIPTION

The C<bif init> command initializes a new bif repository. The
repository is usually a directory named F<.bif> containing the
following files:

=over

=item F<config>:

Configuration information in INI format

=item F<db.sqlite3>:

repository data in an SQLite database

=back

By default F<.bif> is created underneath the current working directory.

    bif init

You can initialize a repository under a different location by giving a
DIRECTORY as the first argument, which will be created if it doesn't
already exist.

    bif init elsewhere

If you are creating a repository for use as a hub then the C<--bare>
option can be used to skip the creation of the F<.bif> directory.

    bif init my-hub --bare

Attempting to initialize an existing repository is considered an error.

=head1 ARGUMENTS & OPTIONS

=over

=item DIRECTORY

The parent location of the respository directory. Defaults to the
current working directory (F<.> or F<$PWD>).

=item --bare

Initialize the repository in F<DIRECTORY> directly instead of
F<DIRECTORY/.bif>.

=back

=head1 SEE ALSO

L<bif>(1)

=head1 AUTHOR

Mark Lawrence E<lt>nomad@null.netE<gt>

=head1 COPYRIGHT AND LICENSE

Copyright 2013-2014 Mark Lawrence <nomad@null.net>

This program is free software; you can redistribute it and/or modify it
under the terms of the GNU General Public License as published by the
Free Software Foundation; either version 3 of the License, or (at your
option) any later version.

