=head1 NAME

bif-list-projects - list projects with task/issue count & progress

=head1 VERSION

0.1.0_10 (2014-04-17)

=head1 SYNOPSIS

    bif list projects [HUB] [OPTIONS...]

=head1 DESCRIPTION

The C<bif list projects> command lists the projects in the local
repository, showing counts of the open and stalled topics, and a
calculated progress percentage.

=head1 ARGUMENTS & OPTIONS

=over

=item HUB

If a hub alias or location is provided then projects hosted by that hub
will be listed instead of only listing local projects. A '*' character
in the statistics columns (topic counts, completion %) is shown for
remote-only projects where the information is not known locally.

=item --status, -s STATUS

Limit the list to projects with a matching status.

=back

=head1 SEE ALSO

L<bif>(1)

=head1 AUTHOR

Mark Lawrence E<lt>nomad@null.netE<gt>

=head1 COPYRIGHT AND LICENSE

Copyright 2013-2014 Mark Lawrence <nomad@null.net>

This program is free software; you can redistribute it and/or modify it
under the terms of the GNU General Public License as published by the
Free Software Foundation; either version 3 of the License, or (at your
option) any later version.

