=head1 NAME

bif-doc-func-update-task - update a task topic

=head1 VERSION

0.1.0_19 (2014-05-08)

=head1 SYNOPSIS

    #!sqlite
    BEGIN;

    INSERT INTO updates(...);

    INSERT INTO func_update_task(
        update_id,  -- integer NOT NULL DEFAULT (currval('updates')),
        id,         -- integer NOT NULL DEFAULT (nextval('topics')),
        status_id,  -- integer
        title       -- varchar
    ) VALUES (...);

    INSERT INTO func_merge_updates DEFAULT VALUES;

    COMMIT;

=head1 DESCRIPTION

func_update_task() adds a task update to an in-progress update, by
inserting a row into L<task_updates|bif-doc-table-task-updates>. As it
just passes the values straight through this function is possibly a
candidate for deletion.

=head1 AFFECTED TABLES

A successful call to func_update_task directly affects the following
tables:

=over

=item * L<task_updates|bif-doc-table-task-updates>

=back

=head1 SEE ALSO

L<bif-doc-table-updates>, L<bif-doc-table-tasks>,
L<bif-doc-func-merge-updates>

=head1 AUTHOR

Mark Lawrence E<lt>nomad@null.netE<gt>

=head1 COPYRIGHT AND LICENSE

Copyright 2013-2014 Mark Lawrence <nomad@null.net>

This program is free software; you can redistribute it and/or modify it
under the terms of the GNU General Public License as published by the
Free Software Foundation; either version 3 of the License, or (at your
option) any later version.

