
=for bif-doc #devintro bif-doc-roadmap - where development is focused

=head1 Development Roadmap

The next few releases of bif aim to make some progress on the
following:

=over

=item * Fix failing (or missing) tests for all CRUD operations

=item * Fleshing out the bif manpage/tutorial

=item * Thorough reference documentation for all commands and modules

=item * Rewrite the synchronisation modules based on AnyEvent/Coro.

=back

Looking further ahead it is hoped that the following challenges can be
addressed:

=over

=item * Add timesheet management

=item * Apply the same synchronisation model to people/contacts, to
provide a distributed address book.

=back

