=head1 Bif Documentation Table of Contents

=head2 Introduction & General Information

=over

=item * L<bif> - the bif manual

=item * L<bif-doc> - bif documentation table of contents (this document)

=item * L<bif-doc-intro> - a hands-on quickstart introduction

=item * L<bif-doc-changelog> - what has changed in each release

=item * L<bif-doc-faq> - frequently asked questions

=back

=head2 Initialisation

=over

=item * L<bif-init> - initialise a bif repository

=back

=head2 Topic Creation

=over

=item * L<bif-new-project> - initialise a bif repository

=item * L<bif-new-task> - initialise a bif repository

=item * L<bif-new-issue> - initialise a bif repository

=back

=head2 Current Information Retrieval

=over

=item * L<bif-list-projects> - initialise a bif repository

=item * L<bif-list-project-status> - initialise a bif repository

=item * L<bif-list-topics> - initialise a bif repository

=item * L<bif-show> - display a topics current status

=item * L<bif-show-hub> - show a repository current status

=item * L<bif-show-update> - dump an update in YAML format

=back

=head2 Historical Information Retrieval

=over

=item * L<bif-log> - review updates/history

=item * L<bif-log-hub> - review a hub's history

=item * L<bif-log-updates> - review all updates in current repository

=back

=head2 Topic Modification

=over

=item * L<bif-drop> - delete a topic or topic update

=item * L<bif-update> - comment on or update a topic

=back

=head2 Distribution, Collaboration & Synchronisation

=over

=item * L<bif-pull-identity> - import project list from a hub

=item * L<bif-pull-hub> - import project list from a hub

=item * L<bif-pull-project> - import a project from a hub

=item * L<bif-push> - push a topic to another project

=item * L<bif-push-hub> - export a hub to a provider

=item * L<bif-push-issue> - send an issue to another project

=item * L<bif-push-project> - export a project to a hub

=item * L<bif-sync> - initialise a bif repository

=back

=head2 Repository & Hub Management

=over

=item * L<bif-upgrade> - upgrade a repository

=item * L<bif-sql> - run an SQL command against the database

=item * L<bifhub> - bif hub management

=item * L<bifsync> - bif synchronization server

=back

=head2 Developer Documentation

=over

=item * L<bif-doc-design> - how and why bif does what it does

=item * L<bif-doc-roadmap> - where development is focused

=back

=head2 Perl Modules

=over

=item * L<App::bif> - initialise a bif repository

=item * L<App::bif::Context> - Context class for bif commands

=item * L<Bif::DB> - initialise a bif repository

=item * L<Bif::DBW> - initialise a bif repository

=item * L<Bif::Role::Sync> - initialise a bif repository

=item * L<Bif::Client> - initialise a bif repository

=item * L<Bif::Server> - initialise a bif repository

=back

=head2 Database Tables & Their Triggers

The documentation pages for database tables have titles like
bif-doc-table-TABLE-NAME.

=over

=item * L<bif-doc-table-default-status>

=item * L<bif-doc-table-hubs>

=item * L<bif-doc-table-issues-tomerge>

=item * L<bif-doc-table-issues-tomerge-status>

=item * L<bif-doc-table-issues>

=item * L<bif-doc-table-issue-status-tomerge>

=item * L<bif-doc-table-issue-status>

=item * L<bif-doc-table-issue-status-updates>

=item * L<bif-doc-table-issue-updates>

=item * L<bif-doc-table-project-issues>

=item * L<bif-doc-table-projects-tomerge>

=item * L<bif-doc-table-project-related-updates>

=item * L<bif-doc-table-projects> - project current meta data

=item * L<bif-doc-table-projects-merkle>

=item * L<bif-doc-table-project-status-tomerge>

=item * L<bif-doc-table-project-status>

=item * L<bif-doc-table-project-status-updates>

=item * L<bif-doc-table-projects-tree>

=item * L<bif-doc-table-project-updates>

=item * L<bif-doc-table-tasks-tomerge>

=item * L<bif-doc-table-tasks>

=item * L<bif-doc-table-task-status-tomerge>

=item * L<bif-doc-table-task-status>

=item * L<bif-doc-table-task-status-updates>

=item * L<bif-doc-table-task-updates>

=item * L<bif-doc-table-topics>

=item * L<bif-doc-table-updates>

=item * L<bif-doc-table-updates-pending>

=item * L<bif-doc-table-updates-tree>

=back

=head2 Database Functions

The documentation pages for database functions have titles like
bif-doc-func-TABLE-NAME.


=over

=item * L<bif-doc-func-import-update>

=item * L<bif-doc-func-import-project>

=item * L<bif-doc-func-import-project-update>

=item * L<bif-doc-func-import-project-status>

=item * L<bif-doc-func-import-project-status-update>

=item * L<bif-doc-func-import-task-status>

=item * L<bif-doc-func-import-task-status-update>

=item * L<bif-doc-func-import-issue-status>

=item * L<bif-doc-func-import-issue-status-update>

=item * L<bif-doc-func-import-task>

=item * L<bif-doc-func-import-task-update>

=item * L<bif-doc-func-import-issue>

=item * L<bif-doc-func-import-issue-update>

=item * L<bif-doc-func-merge-updates>

=item * L<bif-doc-func-new-issue>

=item * L<bif-doc-func-new-issue-status>

=item * L<bif-doc-func-new-project> - add a new project to an update

=item * L<bif-doc-func-new-project-status>

=item * L<bif-doc-func-new-task>

=item * L<bif-doc-func-new-task-status>

=item * L<bif-doc-func-update-issue>

=item * L<bif-doc-func-update-issue-status>

=item * L<bif-doc-func-update-project>

=item * L<bif-doc-func-update-project-status>

=item * L<bif-doc-func-update-task>

=item * L<bif-doc-func-update-task-status>

=back
