=head1 Bif Documentation Overview

=head2 User Documentation

=head3 Introduction & General Information

=over

=item * L<bif> - the bif manual

=item * L<bif-changelog> - what has changed in each release

=item * L<bif-doc> - documentation index (this document)

=item * L<bif-faq> - frequently asked questions

=item * L<bif-intro> - a hands-on quickstart introduction

=back

=head3 Initialisation And Configuration

=over

=item * L<bif-init> - initialise a bif repository

=item * L<bif-config> - initialise a bif repository

=back

=head3 Topic Creation

=over

=item * L<bif-new-project> - initialise a bif repository

=item * L<bif-new-task> - initialise a bif repository

=item * L<bif-new-issue> - initialise a bif repository

=back

=head3 Information Retrieval

=over

=item * L<bif-list-projects> - initialise a bif repository

=item * L<bif-list-project-status> - initialise a bif repository

=item * L<bif-list-topics> - initialise a bif repository

=item * L<bif-log> - review the repository or topic history

=item * L<bif-show> - display a topics current status

=back

=head3 Topic Modification & Collaboration

=over

=item * L<bif-reply> - reply to a comment

=item * L<bif-drop> - delete a topic or topic update

=item * L<bif-push> - push a topic to another project

=item * L<bif-update> - comment on or update a topic

=back

=head3 Project Mirroring & Synchronisation

=over

=item * L<bif-export> - initialise a bif repository

=item * L<bif-import> - initialise a bif repository

=item * L<bif-register> - register with a hub

=item * L<bif-sync> - initialise a bif repository

=back

=head3 Repository & Hub Management

=over

=item * L<bif-upgrade> - upgrade a repository

=item * L<bif-sql> - run an SQLite command against the database

=item * L<bifhub> - bif hub management

=item * L<bifsync> - bif synchronization server

=back


=head2 Developer Documentation

=over

=item * L<bif-design> - how and why bif does what it does

=item * L<bif-roadmap> - where development is focused

=back

=head3 Perl Modules

=over

=item * L<App::bif> - initialise a bif repository

=item * L<App::bif::Util> - initialise a bif repository

=item * L<Bif::DB> - initialise a bif repository

=item * L<Bif::DB::RW> - initialise a bif repository

=item * L<Bif::Sync> - initialise a bif repository

=item * L<Bif::Sync::Client> - initialise a bif repository

=item * L<Bif::Sync::Server> - initialise a bif repository

=back

=head3 Database Tables & Their Triggers

=over

=item * L<Bif::SQLite::table::default_status>

=item * L<Bif::SQLite::table::hubs>

=item * L<Bif::SQLite::table::issue_mergers>

=item * L<Bif::SQLite::table::issue_mergers_status>

=item * L<Bif::SQLite::table::issues>

=item * L<Bif::SQLite::table::issue_status_mergers>

=item * L<Bif::SQLite::table::issue_status>

=item * L<Bif::SQLite::table::issue_status_updates>

=item * L<Bif::SQLite::table::issue_updates>

=item * L<Bif::SQLite::table::links>

=item * L<Bif::SQLite::table::project_issues>

=item * L<Bif::SQLite::table::project_mergers>

=item * L<Bif::SQLite::table::project_prefixes>

=item * L<Bif::SQLite::table::project_related_updates>

=item * L<Bif::SQLite::table::projects> - project current meta data

=item * L<Bif::SQLite::table::project_status_mergers>

=item * L<Bif::SQLite::table::project_status>

=item * L<Bif::SQLite::table::project_status_updates>

=item * L<Bif::SQLite::table::projects_tree>

=item * L<Bif::SQLite::table::project_updates>

=item * L<Bif::SQLite::table::task_mergers>

=item * L<Bif::SQLite::table::tasks>

=item * L<Bif::SQLite::table::task_status_mergers>

=item * L<Bif::SQLite::table::task_statuss>

=item * L<Bif::SQLite::table::task_status_updates>

=item * L<Bif::SQLite::table::task_updates>

=item * L<Bif::SQLite::table::topics>

=item * L<Bif::SQLite::table::updates>

=item * L<Bif::SQLite::table::updates_pending>

=item * L<Bif::SQLite::table::updates_tree>

=back

=head3 Database Functions

=over

=item * L<Bif::SQLite::func_import_update>

=item * L<Bif::SQLite::func_import_project>

=item * L<Bif::SQLite::func_import_project_update>

=item * L<Bif::SQLite::func_import_project_status>

=item * L<Bif::SQLite::func_import_project_status_update>

=item * L<Bif::SQLite::func_import_task_status>

=item * L<Bif::SQLite::func_import_task_status_update>

=item * L<Bif::SQLite::func_import_issue_status>

=item * L<Bif::SQLite::func_import_issue_status_update>

=item * L<Bif::SQLite::func_import_task>

=item * L<Bif::SQLite::func_import_task_update>

=item * L<Bif::SQLite::func_import_issue>

=item * L<Bif::SQLite::func_import_issue_update>

=item * L<Bif::SQLite::func_merge_updates>

=item * L<Bif::SQLite::func_new_issue>

=item * L<Bif::SQLite::func_new_issue_status>

=item * L<Bif::SQLite::func_new_project> - add a new project to an update

=item * L<Bif::SQLite::func_new_project_status>

=item * L<Bif::SQLite::func_new_task>

=item * L<Bif::SQLite::func_new_task_status>

=item * L<Bif::SQLite::func_update_issue>

=item * L<Bif::SQLite::func_update_issue_status>

=item * L<Bif::SQLite::func_update_project>

=item * L<Bif::SQLite::func_update_project_status>

=item * L<Bif::SQLite::func_update_task>

=item * L<Bif::SQLite::func_update_task_status>

=back
