=head1 Bif Developer Documentation

=head2 Developer Introduction

=over

=item * L<bif-doc-design> - how and why bif does what it does

=item * L<bif-doc-roadmap> - where development is focused

=back

=head2 Perl Modules

=over

=item * L<App::bif> - initialise a bif repository

=item * L<App::bif::Context> - Context class for bif commands

=item * L<Bif::DB> - initialise a bif repository

=item * L<Bif::DBW> - initialise a bif repository

=item * L<Bif::Role::Sync> - initialise a bif repository

=item * L<Bif::Client> - initialise a bif repository

=item * L<Bif::Server> - initialise a bif repository

=back

=head2 Database Tables & Their Triggers

The documentation pages for database tables have titles like
bif-doc-table-TABLE-NAME.

=over

=item * L<bif-doc-table-default-status>

=item * L<bif-doc-table-hubs>

=item * L<bif-doc-table-issues-tomerge>

=item * L<bif-doc-table-issues-tomerge-status>

=item * L<bif-doc-table-issues>

=item * L<bif-doc-table-issue-status-tomerge>

=item * L<bif-doc-table-issue-status>

=item * L<bif-doc-table-issue-status-changes>

=item * L<bif-doc-table-issue-changes>

=item * L<bif-doc-table-project-issues>

=item * L<bif-doc-table-projects-tomerge>

=item * L<bif-doc-table-project-related-changes>

=item * L<bif-doc-table-projects> - project current meta data

=item * L<bif-doc-table-projects-merkle>

=item * L<bif-doc-table-project-status-tomerge>

=item * L<bif-doc-table-project-status>

=item * L<bif-doc-table-project-status-changes>

=item * L<bif-doc-table-projects-tree>

=item * L<bif-doc-table-project-changes>

=item * L<bif-doc-table-tasks-tomerge>

=item * L<bif-doc-table-tasks>

=item * L<bif-doc-table-task-status-tomerge>

=item * L<bif-doc-table-task-status>

=item * L<bif-doc-table-task-status-changes>

=item * L<bif-doc-table-task-changes>

=item * L<bif-doc-table-topics>

=item * L<bif-doc-table-changes>

=item * L<bif-doc-table-changes-pending>

=item * L<bif-doc-table-changes-tree>

=back

=head2 Database Functions

The documentation pages for database functions have titles like
bif-doc-func-TABLE-NAME.


=over

=item * L<bif-doc-func-import-change>

=item * L<bif-doc-func-import-project>

=item * L<bif-doc-func-import-project-change>

=item * L<bif-doc-func-import-project-status>

=item * L<bif-doc-func-import-project-status-change>

=item * L<bif-doc-func-import-task-status>

=item * L<bif-doc-func-import-task-status-change>

=item * L<bif-doc-func-import-issue-status>

=item * L<bif-doc-func-import-issue-status-change>

=item * L<bif-doc-func-import-task>

=item * L<bif-doc-func-import-task-change>

=item * L<bif-doc-func-import-issue>

=item * L<bif-doc-func-import-issue-change>

=item * L<bif-doc-func-merge-changes>

=item * L<bif-doc-func-new-issue>

=item * L<bif-doc-func-new-issue-status>

=item * L<bif-doc-func-new-project> - add a new project to an change

=item * L<bif-doc-func-new-project-status>

=item * L<bif-doc-func-new-task>

=item * L<bif-doc-func-new-task-status>

=item * L<bif-doc-func-change-issue>

=item * L<bif-doc-func-change-issue-status>

=item * L<bif-doc-func-change-project>

=item * L<bif-doc-func-change-project-status>

=item * L<bif-doc-func-change-task>

=item * L<bif-doc-func-change-task-status>

=back
